#!/usr/bin/env python3
"""Write the native settings coverage map from the running shell.

Reads `noctalia msg settings-schema` (the native settings registry: every setting, its path and control) and
`~/.config/zynith/zynith.toml` (which surfaces the Zynith UI draws), and writes
06_Reference/configuration/native-settings-coverage.md: for each native setting, where it is edited now.
Run it again after a native change; the map cannot drift from the code because it is read from it.
"""
import json, os, re, subprocess, sys, tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "06_Reference", "configuration", "native-settings-coverage.md")

# native sections whose surface the Zynith UI can draw, and the Zynith page that replaces them
OWNED = {
    "bar": ("bar", "Settings → Bars (`bars.toml`)"),
    "launcher": ("launcher", "Settings → Launcher (`panels.toml [launcher]`)"),
    "control-center": ("control_center", "Settings → Control Panel (`panels.toml [control_panel]`)"),
    "notifications": ("notifications", "Settings → Notifications (`notifications.toml`)"),
    "osd": ("osd", "Settings → On-screen display (`panels.toml [osd]`)"),
    "desktop": ("desktop_widgets", "Settings → Desktop widgets and the editor (`widgets.toml`)"),
}


def redact(segment):
    """Device paths and hardware addresses are this machine's, not documentation."""
    if segment.startswith("/org/freedesktop") or re.search(r"([0-9A-F]{2}[:_]){5}[0-9A-F]{2}", segment, re.I):
        return "<device>"
    return segment


def msg(*args):
    out = subprocess.run(["noctalia", "msg", *args], capture_output=True, text=True, timeout=10)
    if out.returncode != 0 or out.stdout.startswith("error"):
        sys.exit(f"noctalia msg {' '.join(args)}: {out.stdout.strip() or out.stderr.strip()}")
    return json.loads(out.stdout)


def main():
    surfaces = {}
    try:
        surfaces = tomllib.load(open(os.path.expanduser("~/.config/zynith/zynith.toml"), "rb")).get("surfaces", {})
    except OSError:
        pass
    sections = msg("settings-schema")["sections"]
    lines = [
        "# Native settings coverage",
        "",
        "Generated by `scripts/native-settings-coverage.py` from the running shell's settings registry",
        "(`noctalia msg settings-schema`). Every native setting is in one of three places:",
        "",
        "- **Zynith Settings → Shell settings** draws it from the registry and writes it as the native Settings",
        "  would (`settings-set`, a ConfigService override in `settings.toml`, validated by the schema).",
        "- **Native editor**: a whole editor rather than a value (keybinds, idle behaviours, notification filters,",
        "  session actions, template grid). Shell settings shows it with a button that opens the native Settings",
        "  at its section.",
        "- **Superseded**: the setting shapes a native surface that the Zynith UI now draws instead",
        "  (`zynith.toml [surfaces]`); Zynith's own page holds the equivalent. Nothing is removed: switching",
        "  the surface back to native in Settings → Zynith UI makes these settings apply again.",
        "",
        "| Section | Settings | Edited in Shell settings | Native editor | Status |",
        "|---|---:|---:|---:|---|",
    ]
    detail = []
    totals = [0, 0, 0]
    for s in sections:
        if s["count"] == 0:
            continue
        entries = msg("settings-schema", s["id"])["entries"]
        native = [e for e in entries if e["kind"] == "native"]
        owned = OWNED.get(s["id"])
        status = "kept native"
        if owned and surfaces.get(owned[0]) == "zynith":
            status = f"superseded — {owned[1]}"
        elif owned:
            status = f"native surface in use; Zynith equivalent: {owned[1]}"
        lines.append(f"| {s['label']} (`{s['id']}`) | {len(entries)} | {len(entries) - len(native)} | {len(native)} | {status} |")
        totals[0] += len(entries)
        totals[1] += len(entries) - len(native)
        totals[2] += len(native)
        detail.append(f"\n## {s['label']}\n")
        detail.append("| Setting | Path | Control |")
        detail.append("|---|---|---|")
        for e in entries:
            title = e["title"].replace("|", "\\|")
            # a per-device setting is titled with the device's name and address: keep only what it sets
            if any(redact(p) != p for p in e["path"]):
                title = "Per device: " + e["path"][-1].replace("_", " ")
            detail.append(f"| {title} | `{'.'.join(redact(p) for p in e['path'])}` | {e['kind']}{' (advanced)' if e['advanced'] else ''} |")
    lines.append(f"| **All** | **{totals[0]}** | **{totals[1]}** | **{totals[2]}** | |")
    lines += detail
    open(OUT, "w").write("\n".join(lines) + "\n")
    print(f"{totals[0]} settings: {totals[1]} edited in Shell settings, {totals[2]} in native editors -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
